### ISSUE TITLE
Error: Angular Compiler was detected but it was an instance of the wrong class.

### ISSUE THREAD

**Issue by cgrossde** [angular-guru/electron-builder#2]
Hi thanks for this builder :)

I ran into a problem using it:
```
Date: 2018-10-06T16:02:12.578Z
Hash: 67e05c01e41085f478bd
Time: 12720ms
chunk {main} main.js, main.js.map (main) 2.89 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 1.14 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 5.22 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 133 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 271 kB [initial] [rendered]

ERROR in ./frontend/src/main.ts
Module build failed: Error: Angular Compiler was detected but it was an instance of the wrong class.
This likely means you have several @ngtools/webpack packages installed. You can check this with `npm ls @ngtools/webpack`, and then remove the extra copies.
    at Object.ngcLoader (/Users/.../node_modules/@ngtools/webpack/src/loader.js:33:15)
ERROR in ./frontend/src/polyfills.ts
Module build failed: Error: Angular Compiler was detected but it was an instance of the wrong class.
This likely means you have several @ngtools/webpack packages installed. You can check this with `npm ls @ngtools/webpack`, and then remove the extra copies.
    at Object.ngcLoader (/Users/.../node_modules/@ngtools/webpack/src/loader.js:33:15)
ℹ ｢wdm｣: Failed to compile.
```
**npm ls @ngtools/webpack**
```
c-photo@0.0.0 /Users/...
├─┬ @angular-devkit/build-angular@0.7.5
│ └── @ngtools/webpack@6.1.5 
└─┬ @angular-guru/electron-builder@6.1.4
  └─┬ @angular-devkit/build-angular@0.7.5
    └── @ngtools/webpack@6.1.5 
```

I downgraded `@angular-devkit/build-angular` from `0.8.0` to `0.7.5` so they use the same version of ngtools but that didn't seem to help. Do you have any idea what's the issue is here?

**Comment by ashh640** [comment]
Hi,

Thanks for letting me know about the issue. I have published a beta release that will hopefully fix this issue to npm. You can try downloading it using:

`npm install @angular-guru/electron-builder@next`

Let me know if that fixes your issue and if so I will publish the release.

Thanks!

**Comment by cgrossde** [comment]
Wow, that was fast. I just tested it with `@angular-devkit/build-angular` `0.8.0` and `0.7.5` and both work. Thank you!

**Comment by ashley-hunter** [comment]
Great! I'll publish that release! Thanks!
