### ISSUE TITLE
Require is not defined

### ISSUE THREAD

**Issue by brucebrit** [angular-guru/electron-builder#7]
Hi,
Angular-core: 8.2.8
Electron: 6.0.10
@angular-guru/electron-builder: ^8.0.0

I follow the instruction to use this builder, but I go the below error instead.

An error was thrown in afterAll
  **ReferenceError: require is not defined**
      at Object.fs (http://localhost:9876/_karma_webpack_/external "fs":1:1)
      at __webpack_require__ (http://localhost:9876/_karma_webpack_/webpack/bootstrap:79:1)
      at Object../src/app/core/services/FileService/FileService.ts (http://localhost:9876/_karma_webpack_/src/app/core/services/FileService/FileService.ts:1:1)
      at __webpack_require__ (http://localhost:9876/_karma_webpack_/webpack/bootstrap:79:1)
      at Object../src/app/core/services/index.ts (http://localhost:9876/_karma_webpack_/src/app/core/services/index.ts:2:1)
      at __webpack_require__ (http://localhost:9876/_karma_webpack_/webpack/bootstrap:79:1)
      at Object../src/app/app.component.ts (http://localhost:9876/_karma_webpack_/src/app/app.component.ts:2:1)
      at __webpack_require__ (http://localhost:9876/_karma_webpack_/webpack/bootstrap:79:1)
      at Object../src/app/app.component.spec.ts (http://localhost:9876/_karma_webpack_/src/app/app.component.spec.ts:3:1)
      at __webpack_require__ (http://localhost:9876/_karma_webpack_/webpack/bootstrap:79:1)
Chrome 76.0.3809 (Windows 10.0.0): Executed 0 of 0 ERROR (0 secs / 0 secs)
Chrome 76.0.3809 (Windows 10.0.0) ERROR
  An error was thrown in afterAll
  ReferenceError: require is not defined
      at Object.fs (http://localhost:9876/_karma_webpack_/external "fs":1:1)
      at __webpack_require__ (http://localhost:9876/_karma_webpack_/webpack/bootstrap:79:1)
      at Object../src/app/core/services/FileService/FileService.ts (http://localhost:9876/_karma_webpack_/src/app/core/services/FileService/FileService.ts:1:1)
      at __webpack_require__ (http://localhost:9876/_karma_webpack_/webpack/bootstrap:79:1)
      at Object../src/app/core/services/index.ts (http://localhost:9876/_karma_webpack_/src/app/core/services/index.ts:2:1)
      at __webpack_require__ (http://localhost:9876/_karma_webpack_/webpack/bootstrap:79:1)
      at Object../src/app/app.component.ts (http://localhost:9876/_karma_webpack_/src/app/app.component.ts:2:1)
      at __webpack_require__ (http://localhost:9876/_karma_webpack_/webpack/bootstrap:79:1)
      at Object../src/app/app.component.spec.ts (http://localhost:9876/_karma_webpack_/src/app/app.component.spec.ts:3:1)
Chrome 76.0.3809 (Windows 10.0.0): Executed 0 of 0 ERROR (0.07 secs / 0 secs)

**Comment by Trindade7** [comment]
I've got the same error. have you to solved it?

**Comment by lxcodev** [comment]
+1
Same error when using Karma test.

**Comment by MatteoMeil** [comment]
I solved setting
```json
"webPreferences": {
    "nodeIntegration": true
}
```
when instatiating a new Electron window (i.e.: `new BrowserWindow`)
